services:
  redis:
    image: redis:7.4.1
    container_name: redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - digital-shop-network
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']

  backend:
    image: doankietdev/digital-world-shop-api:1.0.0
    container_name: backend
    env_file: backend/.env
    ports:
      - '${BACKEND_PORT}:5600'
    networks:
      - digital-shop-network
    depends_on:
      - redis

  frontend:
    image: doankietdev/digital-world-shop-web:1.0.0
    container_name: frontend
    env_file: ./frontend/.env
    ports:
      - '${FRONTEND_PORT}:80'
    networks:
      - digital-shop-network
    depends_on:
      - backend

  reverse-proxy:
    image: nginx:1.23-alpine
    container_name: reverse-proxy
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    networks:
      - digital-shop-network
    depends_on:
      - backend
      - frontend
networks:
  digital-shop-network:
    driver: bridge
